version: '3'

services:
  ha-hue-emulator:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    restart: always
    stop_grace_period: 0s
    ports:
      - '80:80'
      - '443:443'
      - '1900:1900/udp'
      - '2100:2100/udp'
      - '1982:1982/udp'